### ISSUE TITLE
data augmentation

### ISSUE THREAD

**Issue by pgbrodrick** [pgbrodrick/bfg-nets#93]
Hook up more comprehensive data augmentation (e.g. https://imgaug.readthedocs.io/en/latest/)

**Comment by nsfabina** [comment]
Looking at options I'm seeing:
keras image preprocessing module - limited augmentations
augmentor - most augmentations, 3k stars, 20 contribs, last commit jul 26
albumentations - most augmentations, 3k stars, 31 contrive, last commit 3 days ago
imgaug - only 30 stars, last commit jun 15

Given that, I'll probably implement albumentations. Keras might be a better long-term bet, but I think we'd benefit from more augmentations.

(Augmentor has a neat occlusion option, where part of the image is blocked out, which could be useful for simulating clouds. Unfortunately, this isn't perfect because it's just random noise. There's probably a better way for us to do this, even if it means having someone build up a small library of clouds that can be superimposed.)

**Comment by pgbrodrick** [comment]
Looking through briefly I like the options in albumentations.  I think for clouds we can (and should) hook up a custom algorithm, as we're really going to want to get relative cloud-shadow position and various categories and degrees of cloud included.

**Comment by nsfabina** [comment]
Done in https://github.com/pgbrodrick/bfg-nets/pull/97
